#!/usr/bin/env bun
/**
 * Generates setup-manifest.ts with embedded file imports.
 * Run before compilation to discover and embed all setup files.
 *
 * Usage: bun run scripts/generate-setup-manifest.ts
 */

import { readdirSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';

const SETUP_DIR = 'setup';
const OUTPUT_FILE = 'generated/setup-manifest.ts';

interface FileEntry {
    /** Path relative to setup/ (e.g., ".claude/settings.local.json") */
    relativePath: string;
    /** Safe variable name for import */
    importName: string;
}

/**
 * Recursively scan a directory and return all files.
 */
function getFiles(dir: string, baseDir: string = dir): FileEntry[] {
    const entries: FileEntry[] = [];

    for (const entry of readdirSync(dir)) {
        const fullPath = join(dir, entry);
        const stat = statSync(fullPath);

        if (stat.isDirectory()) {
            entries.push(...getFiles(fullPath, baseDir));
        } else {
            const relativePath = relative(baseDir, fullPath);
            // Create safe import name: .claude/foo/bar.md -> file_claude_foo_bar_md
            const importName =
                'file_' +
                relativePath
                    .replace(/^\./, '') // Remove leading dot
                    .replace(/[^a-zA-Z0-9]/g, '_')
                    .replace(/_+/g, '_')
                    .replace(/^_/, '')
                    .replace(/_$/, '');
            entries.push({ relativePath, importName });
        }
    }

    return entries;
}

/**
 * Generate the manifest TypeScript file.
 */
function generateManifest(): void {
    const files = getFiles(SETUP_DIR);

    if (files.length === 0) {
        console.error(`Error: No files found in ${SETUP_DIR}/`);
        process.exit(1);
    }

    // Generate import statements with { type: "file" } attribute
    const imports = files
        .map(f => `import ${f.importName} from '../setup/${f.relativePath}' with { type: 'file' };`)
        .join('\n');

    // Generate manifest entries
    const manifestEntries = files
        .map(f => `    { relativePath: '${f.relativePath}', embeddedPath: ${f.importName} },`)
        .join('\n');

    const content = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-setup-manifest.ts
 *
 * This file embeds all setup files into the compiled binary using
 * Bun's file import attribute. Regenerate after modifying setup/ contents.
 */

${imports}

export interface SetupFile {
    /** Path relative to setup/ folder (e.g., ".claude/settings.local.json") */
    relativePath: string;
    /** Path to embedded file (bun internal path or dev file path) */
    embeddedPath: string;
}

export const SETUP_FILES: SetupFile[] = [
${manifestEntries}
];

/**
 * Check if running from compiled binary (embedded files contain $bunfs in path)
 */
export function isCompiled(): boolean {
    return SETUP_FILES.length > 0 && SETUP_FILES[0].embeddedPath.includes('$bunfs');
}
`;

    // Ensure generated/ directory exists
    mkdirSync(dirname(OUTPUT_FILE), { recursive: true });
    writeFileSync(OUTPUT_FILE, content, 'utf-8');

    console.log(`Generated ${OUTPUT_FILE} with ${files.length} files:`);
    files.forEach(f => console.log(`  - ${f.relativePath}`));
}

generateManifest();
